#include "sicgl/compositors.h"
#include "tests/utilities.h"
#include "utils.h"

DEFINE_UNREFERENCED_COMPOSITOR_TEST(bitwise_and, compositor_bitwise_and)
DEFINE_UNREFERENCED_COMPOSITOR_TEST(bitwise_or, compositor_bitwise_or)
DEFINE_UNREFERENCED_COMPOSITOR_TEST(bitwise_xor, compositor_bitwise_xor)
DEFINE_UNREFERENCED_COMPOSITOR_TEST(bitwise_nand, compositor_bitwise_nand)
DEFINE_UNREFERENCED_COMPOSITOR_TEST(bitwise_nor, compositor_bitwise_nor)
DEFINE_UNREFERENCED_COMPOSITOR_TEST(bitwise_xnor, compositor_bitwise_xnor)
