# continuous integration
name: ci

on:
  push:
    branches: [ "main" ]
  pull_request:
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      # check out the repo
      - uses: actions/checkout@v3
        with:
          submodules: true

      # install clang-format
      - name: install clang-format
        run: |
          sudo apt update
          sudo apt install clang-format
          clang-format --version

      # lint using clang-format
      - name: clang-format lint
        run: |
          ./tools/third-party/run-clang-format/run-clang-format.py -r src include test
  
  test:
    runs-on: ubuntu-latest
    steps:
      # check out the repo
      - uses: actions/checkout@v3

      # install tools
      - name: install tools
        run: |
          sudo apt-get update -y && sudo apt-get install -y cmake

      # update submodules
      - name: update submodules
        run: git submodule update --init --recursive

      # make build dir
      - name: prepare build
        run: mkdir build

      # build and install libgd
      - name: install libgd
        run: |
          cd third-party/libgd
          mkdir build
          cd build
          cmake -DBUILD_TEST=1 ..
          cmake --build .
          make install DESTDIR=../../../build/libgd

      # build
      - name: build tests
        run: |
          cd build
          cmake -DDEBUG=true ..
          cmake --build .
      
      # test
      - name: run tests
        run: ./tools/run-tests.sh
