# continuous integration
name: ci

on:
  push:
    branches: [ "main" ]
  pull_request:
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      # check out the repo
      - uses: actions/checkout@v3

      # lint using clang-format
      - name: clang-format lint
        uses: DoozyX/clang-format-lint-action@v0.14
        with:
          source: 'src include test'
          clangFormatVersion: 14
  
  test:
    runs-on: ubuntu-latest
    steps:
      # check out the repo
      - uses: actions/checkout@v3

      # install tools
      - name: install tools
        run: |
          sudo apt-get update -y && sudo apt-get install -y cmake

      # update submodules
      - name: update submodules
        run: git submodule update --init --recursive

      # build
      - name: build tests
        run: |
          mkdir build
          cd build
          cmake ..
          cmake --build .
          find . -regex '\.\/test_[^\.]*$' -exec '{}' -v \;
